//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 06:46:41 PM IST 
//


package cpm.prashanth.spring.soap.api.alarmdetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for alarmDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="alarmDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alarmId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alarmEquipment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alarmDateAndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="alarmDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "alarmDetails", propOrder = {
    "alarmId",
    "alarmEquipment",
    "alarmDateAndTime",
    "alarmDescription"
})
public class AlarmDetails {

    @XmlElement(required = true)
    protected String alarmId;
    @XmlElement(required = true)
    protected String alarmEquipment;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar alarmDateAndTime;
    @XmlElement(required = true)
    protected String alarmDescription;

    /**
     * Gets the value of the alarmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmId() {
        return alarmId;
    }

    /**
     * Sets the value of the alarmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmId(String value) {
        this.alarmId = value;
    }

    /**
     * Gets the value of the alarmEquipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmEquipment() {
        return alarmEquipment;
    }

    /**
     * Sets the value of the alarmEquipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmEquipment(String value) {
        this.alarmEquipment = value;
    }

    /**
     * Gets the value of the alarmDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAlarmDateAndTime() {
        return alarmDateAndTime;
    }

    /**
     * Sets the value of the alarmDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAlarmDateAndTime(XMLGregorianCalendar value) {
        this.alarmDateAndTime = value;
    }

    /**
     * Gets the value of the alarmDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmDescription() {
        return alarmDescription;
    }

    /**
     * Sets the value of the alarmDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmDescription(String value) {
        this.alarmDescription = value;
    }

}
