//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 06:46:41 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://prashanth.cpm/spring/soap/api/alarmdetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cpm.prashanth.spring.soap.api.alarmdetails;
